const employees = [{
  full_name: 'Employee-1',
  salary: 1000,
  address: 'Address-1',
  manager: null,
  department_no: null,
},
{
  full_name: 'Employee-2',
  salary: 5000,
  address: 'Address-2',
  manager: 1,
  department_no: null,
},
{
  full_name: 'Employee-3',
  salary: 4000,
  address: 'Address-3',
  manager: 2,
  department_no: null,
},
{
  full_name: 'Employee-4',
  salary: 3000,
  address: 'Address-4',
  manager: 3,
  department_no: 111,
},
{
  full_name: 'Employee-5',
  salary: 3000,
  address: 'Address-5',
  manager: 3,
  department_no: 111,
},
{
  full_name: 'Employee-6',
  salary: 3000,
  address: 'Address-6',
  manager: 3,
  department_no: 112,
},
{
  full_name: 'Employee-7',
  salary: 3000,
  address: 'Address-7',
  manager: 3,
  department_no: 112,
},
{
  full_name: 'Employee-8',
  salary: 3000,
  address: 'Address-8',
  manager: 3,
  department_no: 112,
},
{
  full_name: 'Employee-9',
  salary: 4000,
  address: 'Address-9',
  manager: 2,
  department_no: null,
},
{
  full_name: 'Employee-10',
  salary: 3000,
  address: 'Address-10',
  manager: 9,
  department_no: 114,
},
{
  full_name: 'Employee-11',
  salary: 3000,
  address: 'Address-11',
  manager: 9,
  department_no: 114,
},
{
  full_name: 'Employee-12',
  salary: 3000,
  address: 'Address-12',
  manager: 9,
  department_no: 115,
},
{
  full_name: 'Employee-13',
  salary: 3000,
  address: 'Address-13',
  manager: 9,
  department_no: 115,
},
{
  full_name: 'Employee-14',
  salary: 3000,
  address: 'Address-14',
  manager: 9,
  department_no: 115,
},
{
  full_name: 'Employee-15',
  salary: 4000,
  address: 'Address-15',
  manager: 2,
  department_no: null,
},
{
  full_name: 'Employee-16',
  salary: 3000,
  address: 'Address-16',
  manager: 15,
  department_no: 116,
},
{
  full_name: 'Employee-17',
  salary: 3000,
  address: 'Address-17',
  manager: 15,
  department_no: 117,
},
{
  full_name: 'Employee-18',
  salary: 3000,
  address: 'Address-19',
  manager: 15,
  department_no: 118,
},
{
  full_name: 'Employee-19',
  salary: 3000,
  address: 'Address-19',
  manager: 15,
  department_no: 119,
},
{
  full_name: 'Employee-20',
  salary: 3000,
  address: '20',
  manager: 15,
  department_no: 120,
},
];

const departments = [{
  dept_no: 111,
  title: 'Callback Cats',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
  address: '1175  Dale Avenue, New York',
},
{
  dept_no: 112,
  title: 'Data Pirates',
  description: 'sed do eiusmod tempor incididunt ut labore et dolore',
  address: '2847  James Martin Circle, New York',
},
{
  dept_no: 113,
  title: 'Hypertext Assassins',
  description: 'incididunt ut labore et dolore magna aliqua',
  address: '1421  Bagwell Avenue, New York',
},
{
  dept_no: 114,
  title: 'Software Chasers',
  description: 'Ut enim ad minim veniam',
  address: '3820  Goodwin Avenue, New York',
},
{
  dept_no: 115,
  title: 'Query Language Spies',
  description: 'quis nostrud exercitation ullamco',
  address: '3238  McVaney Road, New York',
},
{
  dept_no: 116,
  title: 'Binary Beasts',
  description: 'laboris nisi ut aliquip ex ea commodo consequat',
  address: '870  Carriage Court, Washington',
},
{
  dept_no: 117,
  title: 'App Monsters',
  description: 'Duis aute irure dolor in reprehenderit',
  address: '4334  Tyler Avenue, Washington',
},
{
  dept_no: 118,
  title: 'Pseudo Program Nerds',
  description: 'voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  address: '362  Dennison Street, Washington',
},
{
  dept_no: 119,
  title: 'Algorithm Unlock',
  description: 'Excepteur sint occaecat cupidatat non proident',
  address: '1468  Virginia Street, Washington',
},
{
  dept_no: 120,
  title: 'Kernel Ponies',
  description: 'sunt in culpa qui officia deserunt mollit anim id est laborum',
  address: '1143  Peck Street, Washington',
},
];

module.exports = {
  employees,
  departments
};